// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterRequest) Reset() {
	*x = UserRegisterRequest{}
	mi := &file_internal_grpc_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterRequest) ProtoMessage() {}

func (x *UserRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=user_id,json=UserID,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterResponse) Reset() {
	*x = UserRegisterResponse{}
	mi := &file_internal_grpc_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterResponse) ProtoMessage() {}

func (x *UserRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterResponse.ProtoReflect.Descriptor instead.
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegisterResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

var File_internal_grpc_grpc_proto protoreflect.FileDescriptor

const file_internal_grpc_grpc_proto_rawDesc = "" +
	"\n" +
	"\x18internal/grpc/grpc.proto\x12\x04grpc\"G\n" +
	"\x13UserRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"/\n" +
	"\x14UserRegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06UserID2V\n" +
	"\x11GophKeeperService\x12A\n" +
	"\bRegister\x12\x19.grpc.UserRegisterRequest\x1a\x1a.grpc.UserRegisterResponseB\vZ\tgrpc/grpcb\x06proto3"

var (
	file_internal_grpc_grpc_proto_rawDescOnce sync.Once
	file_internal_grpc_grpc_proto_rawDescData []byte
)

func file_internal_grpc_grpc_proto_rawDescGZIP() []byte {
	file_internal_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_internal_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_grpc_proto_rawDesc), len(file_internal_grpc_grpc_proto_rawDesc)))
	})
	return file_internal_grpc_grpc_proto_rawDescData
}

var file_internal_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_grpc_proto_goTypes = []any{
	(*UserRegisterRequest)(nil),  // 0: grpc.UserRegisterRequest
	(*UserRegisterResponse)(nil), // 1: grpc.UserRegisterResponse
}
var file_internal_grpc_grpc_proto_depIdxs = []int32{
	0, // 0: grpc.GophKeeperService.Register:input_type -> grpc.UserRegisterRequest
	1, // 1: grpc.GophKeeperService.Register:output_type -> grpc.UserRegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_grpc_proto_init() }
func file_internal_grpc_grpc_proto_init() {
	if File_internal_grpc_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_grpc_proto_rawDesc), len(file_internal_grpc_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_internal_grpc_grpc_proto_depIdxs,
		MessageInfos:      file_internal_grpc_grpc_proto_msgTypes,
	}.Build()
	File_internal_grpc_grpc_proto = out.File
	file_internal_grpc_grpc_proto_goTypes = nil
	file_internal_grpc_grpc_proto_depIdxs = nil
}
