// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/grpc/private.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextCreateRequest) Reset() {
	*x = TextCreateRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCreateRequest) ProtoMessage() {}

func (x *TextCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextCreateRequest.ProtoReflect.Descriptor instead.
func (*TextCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{0}
}

func (x *TextCreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_internal_grpc_private_proto protoreflect.FileDescriptor

const file_internal_grpc_private_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/grpc/private.proto\x12\x04grpc\"-\n" +
	"\x11TextCreateRequest\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2W\n" +
	"\x18GophKeeperPrivateService\x12;\n" +
	"\n" +
	"TextCreate\x12\x17.grpc.TextCreateRequest\x1a\x14.grpc.CreateResponseB\vZ\tgrpc/grpcb\x06proto3"

var (
	file_internal_grpc_private_proto_rawDescOnce sync.Once
	file_internal_grpc_private_proto_rawDescData []byte
)

func file_internal_grpc_private_proto_rawDescGZIP() []byte {
	file_internal_grpc_private_proto_rawDescOnce.Do(func() {
		file_internal_grpc_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_private_proto_rawDesc), len(file_internal_grpc_private_proto_rawDesc)))
	})
	return file_internal_grpc_private_proto_rawDescData
}

var file_internal_grpc_private_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_private_proto_goTypes = []any{
	(*TextCreateRequest)(nil), // 0: grpc.TextCreateRequest
	(*CreateResponse)(nil),    // 1: grpc.CreateResponse
}
var file_internal_grpc_private_proto_depIdxs = []int32{
	0, // 0: grpc.GophKeeperPrivateService.TextCreate:input_type -> grpc.TextCreateRequest
	1, // 1: grpc.GophKeeperPrivateService.TextCreate:output_type -> grpc.CreateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_private_proto_init() }
func file_internal_grpc_private_proto_init() {
	if File_internal_grpc_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_private_proto_rawDesc), len(file_internal_grpc_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_private_proto_goTypes,
		DependencyIndexes: file_internal_grpc_private_proto_depIdxs,
		MessageInfos:      file_internal_grpc_private_proto_msgTypes,
	}.Build()
	File_internal_grpc_private_proto = out.File
	file_internal_grpc_private_proto_goTypes = nil
	file_internal_grpc_private_proto_depIdxs = nil
}
