// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/grpc/private.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *_struct.Struct        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       *_struct.ListValue     `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetSecrets() *_struct.ListValue {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       *_struct.ListValue     `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetSecrets() *_struct.ListValue {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       *_struct.ListValue     `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetSecrets() *_struct.ListValue {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *_struct.Struct        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateRequest) GetData() *_struct.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       *_struct.ListValue     `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetSecrets() *_struct.ListValue {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DeleteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{9}
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadRequest_Metadata
	//	*UploadRequest_Chunk
	Data          isUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{10}
}

func (x *UploadRequest) GetData() isUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Data interface {
	isUploadRequest_Data()
}

type UploadRequest_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Metadata) isUploadRequest_Data() {}

func (*UploadRequest_Chunk) isUploadRequest_Data() {}

type Metadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileName        string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileContentType string                 `protobuf:"bytes,2,opt,name=file_content_type,json=fileContentType,proto3" json:"file_content_type,omitempty"`
	FileSize        int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileOffset      int64                  `protobuf:"varint,4,opt,name=file_offset,json=fileOffset,proto3" json:"file_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_internal_grpc_private_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{11}
}

func (x *Metadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Metadata) GetFileContentType() string {
	if x != nil {
		return x.FileContentType
	}
	return ""
}

func (x *Metadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Metadata) GetFileOffset() int64 {
	if x != nil {
		return x.FileOffset
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       *_struct.ListValue     `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{12}
}

func (x *UploadResponse) GetSecrets() *_struct.ListValue {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type UploadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatusRequest) Reset() {
	*x = UploadStatusRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatusRequest) ProtoMessage() {}

func (x *UploadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatusRequest.ProtoReflect.Descriptor instead.
func (*UploadStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{13}
}

func (x *UploadStatusRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UploadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileOffset    int64                  `protobuf:"varint,1,opt,name=file_offset,json=fileOffset,proto3" json:"file_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatusResponse) Reset() {
	*x = UploadStatusResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatusResponse) ProtoMessage() {}

func (x *UploadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatusResponse.ProtoReflect.Descriptor instead.
func (*UploadStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{14}
}

func (x *UploadStatusResponse) GetFileOffset() int64 {
	if x != nil {
		return x.FileOffset
	}
	return 0
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileOffset    int64                  `protobuf:"varint,2,opt,name=file_offset,json=fileOffset,proto3" json:"file_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_internal_grpc_private_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DownloadRequest) GetFileOffset() int64 {
	if x != nil {
		return x.FileOffset
	}
	return 0
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	FileOffset    int64                  `protobuf:"varint,2,opt,name=file_offset,json=fileOffset,proto3" json:"file_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_internal_grpc_private_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_private_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_private_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *DownloadResponse) GetFileOffset() int64 {
	if x != nil {
		return x.FileOffset
	}
	return 0
}

var File_internal_grpc_private_proto protoreflect.FileDescriptor

const file_internal_grpc_private_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/grpc/private.proto\x12\x04grpc\x1a\x1cgoogle/protobuf/struct.proto\"P\n" +
	"\rCreateRequest\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"F\n" +
	"\x0eCreateResponse\x124\n" +
	"\asecrets\x18\x01 \x01(\v2\x1a.google.protobuf.ListValueR\asecrets\"0\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"C\n" +
	"\vGetResponse\x124\n" +
	"\asecrets\x18\x01 \x01(\v2\x1a.google.protobuf.ListValueR\asecrets\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"D\n" +
	"\fListResponse\x124\n" +
	"\asecrets\x18\x01 \x01(\v2\x1a.google.protobuf.ListValueR\asecrets\"`\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"F\n" +
	"\x0eUpdateResponse\x124\n" +
	"\asecrets\x18\x01 \x01(\v2\x1a.google.protobuf.ListValueR\asecrets\"3\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x10\n" +
	"\x0eDeleteResponse\"]\n" +
	"\rUploadRequest\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0e.grpc.MetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x91\x01\n" +
	"\bMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12*\n" +
	"\x11file_content_type\x18\x02 \x01(\tR\x0ffileContentType\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1f\n" +
	"\vfile_offset\x18\x04 \x01(\x03R\n" +
	"fileOffset\"F\n" +
	"\x0eUploadResponse\x124\n" +
	"\asecrets\x18\x01 \x01(\v2\x1a.google.protobuf.ListValueR\asecrets\"2\n" +
	"\x13UploadStatusRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"7\n" +
	"\x14UploadStatusResponse\x12\x1f\n" +
	"\vfile_offset\x18\x01 \x01(\x03R\n" +
	"fileOffset\"B\n" +
	"\x0fDownloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vfile_offset\x18\x02 \x01(\x03R\n" +
	"fileOffset\"I\n" +
	"\x10DownloadResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1f\n" +
	"\vfile_offset\x18\x02 \x01(\x03R\n" +
	"fileOffset2\xd2\x03\n" +
	"\x18GophKeeperPrivateService\x123\n" +
	"\x06Create\x12\x13.grpc.CreateRequest\x1a\x14.grpc.CreateResponse\x12*\n" +
	"\x03Get\x12\x10.grpc.GetRequest\x1a\x11.grpc.GetResponse\x12-\n" +
	"\x04List\x12\x11.grpc.ListRequest\x1a\x12.grpc.ListResponse\x123\n" +
	"\x06Update\x12\x13.grpc.UpdateRequest\x1a\x14.grpc.UpdateResponse\x123\n" +
	"\x06Delete\x12\x13.grpc.DeleteRequest\x1a\x14.grpc.DeleteResponse\x12H\n" +
	"\x0fGetUploadStatus\x12\x19.grpc.UploadStatusRequest\x1a\x1a.grpc.UploadStatusResponse\x125\n" +
	"\x06Upload\x12\x13.grpc.UploadRequest\x1a\x14.grpc.UploadResponse(\x01\x12;\n" +
	"\bDownload\x12\x15.grpc.DownloadRequest\x1a\x16.grpc.DownloadResponse0\x01B\vZ\tgrpc/grpcb\x06proto3"

var (
	file_internal_grpc_private_proto_rawDescOnce sync.Once
	file_internal_grpc_private_proto_rawDescData []byte
)

func file_internal_grpc_private_proto_rawDescGZIP() []byte {
	file_internal_grpc_private_proto_rawDescOnce.Do(func() {
		file_internal_grpc_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_private_proto_rawDesc), len(file_internal_grpc_private_proto_rawDesc)))
	})
	return file_internal_grpc_private_proto_rawDescData
}

var file_internal_grpc_private_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_grpc_private_proto_goTypes = []any{
	(*CreateRequest)(nil),        // 0: grpc.CreateRequest
	(*CreateResponse)(nil),       // 1: grpc.CreateResponse
	(*GetRequest)(nil),           // 2: grpc.GetRequest
	(*GetResponse)(nil),          // 3: grpc.GetResponse
	(*ListRequest)(nil),          // 4: grpc.ListRequest
	(*ListResponse)(nil),         // 5: grpc.ListResponse
	(*UpdateRequest)(nil),        // 6: grpc.UpdateRequest
	(*UpdateResponse)(nil),       // 7: grpc.UpdateResponse
	(*DeleteRequest)(nil),        // 8: grpc.DeleteRequest
	(*DeleteResponse)(nil),       // 9: grpc.DeleteResponse
	(*UploadRequest)(nil),        // 10: grpc.UploadRequest
	(*Metadata)(nil),             // 11: grpc.Metadata
	(*UploadResponse)(nil),       // 12: grpc.UploadResponse
	(*UploadStatusRequest)(nil),  // 13: grpc.UploadStatusRequest
	(*UploadStatusResponse)(nil), // 14: grpc.UploadStatusResponse
	(*DownloadRequest)(nil),      // 15: grpc.DownloadRequest
	(*DownloadResponse)(nil),     // 16: grpc.DownloadResponse
	(*_struct.Struct)(nil),       // 17: google.protobuf.Struct
	(*_struct.ListValue)(nil),    // 18: google.protobuf.ListValue
}
var file_internal_grpc_private_proto_depIDxs = []int32{
	17, // 0: grpc.CreateRequest.data:type_name -> google.protobuf.Struct
	18, // 1: grpc.CreateResponse.secrets:type_name -> google.protobuf.ListValue
	18, // 2: grpc.GetResponse.secrets:type_name -> google.protobuf.ListValue
	18, // 3: grpc.ListResponse.secrets:type_name -> google.protobuf.ListValue
	17, // 4: grpc.UpdateRequest.data:type_name -> google.protobuf.Struct
	18, // 5: grpc.UpdateResponse.secrets:type_name -> google.protobuf.ListValue
	11, // 6: grpc.UploadRequest.metadata:type_name -> grpc.Metadata
	18, // 7: grpc.UploadResponse.secrets:type_name -> google.protobuf.ListValue
	0,  // 8: grpc.GophKeeperPrivateService.Create:input_type -> grpc.CreateRequest
	2,  // 9: grpc.GophKeeperPrivateService.Get:input_type -> grpc.GetRequest
	4,  // 10: grpc.GophKeeperPrivateService.List:input_type -> grpc.ListRequest
	6,  // 11: grpc.GophKeeperPrivateService.Update:input_type -> grpc.UpdateRequest
	8,  // 12: grpc.GophKeeperPrivateService.Delete:input_type -> grpc.DeleteRequest
	13, // 13: grpc.GophKeeperPrivateService.GetUploadStatus:input_type -> grpc.UploadStatusRequest
	10, // 14: grpc.GophKeeperPrivateService.Upload:input_type -> grpc.UploadRequest
	15, // 15: grpc.GophKeeperPrivateService.Download:input_type -> grpc.DownloadRequest
	1,  // 16: grpc.GophKeeperPrivateService.Create:output_type -> grpc.CreateResponse
	3,  // 17: grpc.GophKeeperPrivateService.Get:output_type -> grpc.GetResponse
	5,  // 18: grpc.GophKeeperPrivateService.List:output_type -> grpc.ListResponse
	7,  // 19: grpc.GophKeeperPrivateService.Update:output_type -> grpc.UpdateResponse
	9,  // 20: grpc.GophKeeperPrivateService.Delete:output_type -> grpc.DeleteResponse
	14, // 21: grpc.GophKeeperPrivateService.GetUploadStatus:output_type -> grpc.UploadStatusResponse
	12, // 22: grpc.GophKeeperPrivateService.Upload:output_type -> grpc.UploadResponse
	16, // 23: grpc.GophKeeperPrivateService.Download:output_type -> grpc.DownloadResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_grpc_private_proto_init() }
func file_internal_grpc_private_proto_init() {
	if File_internal_grpc_private_proto != nil {
		return
	}
	file_internal_grpc_private_proto_msgTypes[10].OneofWrappers = []any{
		(*UploadRequest_Metadata)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_private_proto_rawDesc), len(file_internal_grpc_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_private_proto_goTypes,
		DependencyIndexes: file_internal_grpc_private_proto_depIDxs,
		MessageInfos:      file_internal_grpc_private_proto_msgTypes,
	}.Build()
	File_internal_grpc_private_proto = out.File
	file_internal_grpc_private_proto_goTypes = nil
	file_internal_grpc_private_proto_depIDxs = nil
}
